### ISSUE TITLE
Move code to root folder of studentified project

### ISSUE THREAD

**Issue by adpi2** [lunatech-labs/lunatech-scala-2-to-scala3-course#106]
I find it not convenient that the sbt project is in the `code` folder and not in the root folder of the studentified project. I would prefer to have everything in the same folder so that I can run all the commands (`git`, `cmtc` and `sbt`) from the same working directory.

**Comment by eloots** [comment]
Instead of moving the `code` to the root folder, I would keep is as-is, but apply the following changes:

- Instead of initialising the repo as a git repo from the root folder, only initialise the `code` folder as a `git` repo. That should be an easy change (applied as an overall change in the `cmta` command which is used to generate the student repo.)
- With the change in the previous item, both `git` and `sbt` can be used in the `code` folder.
- As far as `cmtc` is concerned, I see that as a minor point as the instructions tell that the first thing a student should do is to run the `cmtc set-current-course -s <course-repo-folder>. From then on, all `cmtc` invocations will be applied on the current course.

**Comment by eloots** [comment]
What you requested is now possible via https://github.com/lunatech-labs/course-management-tools/pull/242

The only thing that is necessary is to set `cmt.studentified-repo-active-exercise-folder = .` in the project's course management configuration file.
